### ISSUE TITLE
[BUG]游戏外不显示MOD

### ISSUE THREAD

**Issue by Mitpoppy** [Minxyzgo/RWPP#15]
已提前在游戏内的设置页面开启使用外部存储并且给了权限
游戏内在设置页面进入模组页面显示全部MOD
![](https://img.someo.top/file/44f16d85074e8eb2a11b0.jpg)
但在游戏主界面进入模组页面并不显示模组，已重启游戏+手机，并且多次刷新，使用内部文件正常显示
![](https://img.someo.top/file/473e53724ff10acc50ba0.jpg)

**Comment by Minxyzgo** [comment]
这个不太清楚，我这边是正常的，而且实现是直接拿的游戏内mod列表
点击update试试？
