### ISSUE TITLE
手机版主页ui界面

### ISSUE THREAD

**Issue by Mitpoppy** [Minxyzgo/RWPP#26]
手机版的主页ui太大了，可以适当小一点，现在的ui需要滑动才能显示全部内容，可以把全部ui缩小一点，让内容可以全部显示出来，而不用滑动

**Comment by Mitpoppy** [comment]
特别是上面的logo，你可以选择半透明方式在下面图层，然后上面渐变透明度显示ui

**Comment by Minxyzgo** [comment]
采取横向滚动实现
