### ISSUE TITLE
大部分界面输入框ui显示问题

### ISSUE THREAD

**Issue by Mitpoppy** [Minxyzgo/RWPP#33]
基本所有输入框都有这个问题，正常查看输入框没问题，但是一旦点击输入框那么会把输入框内文字移动上去并加一个透明框，这个透明框我觉得不需要，因为会覆盖黑色部分，导致文字看起来挺突出，你可以参考网页前端mdui框架的设计，直接移动上去去掉框的线条，但是整天不变，因为文字的颜色本身就和其他颜色区分开了
（图片为左上角名字输入框例子）
![Screenshot_20240814_230504.jpg](https://github.com/user-attachments/assets/3d2cfc85-09dd-462e-84ec-85fe55d0ccf1)

**Comment by Minxyzgo** [comment]
没有看懂

**Comment by Mitpoppy** [comment]
> 没有看懂

就是说输入框里面文字移动到框上，框上面的文字会加一个类似图片的边，这个边有点难受

**Comment by Mitpoppy** [comment]
> 没有看懂
就好像你直接把一张图片移到框上去然后把这个框的边缘覆盖了

**Comment by Minxyzgo** [comment]
> > 没有看懂
> 
> 就是说输入框里面文字移动到框上，框上面的文字会加一个类似图片的边，这个边有点难受

无解，这个算是android原生的东西，动不了

**Comment by Mitpoppy** [comment]
> > > 没有看懂
> > 
> > 就是说输入框里面文字移动到框上，框上面的文字会加一个类似图片的边，这个边有点难受
> 
> 无解，这个算是android原生的东西，动不了

行吧
