### ISSUE TITLE
大部分弹出界面可以考虑不用加关闭按钮

### ISSUE THREAD

**Issue by Mitpoppy** [Minxyzgo/RWPP#35]
就比如创建房间这个![Screenshot_20240814_232454.jpg](https://github.com/user-attachments/assets/e80ba4fb-81db-40e7-b603-e99de3ff654a)

加了按钮反而不美观，可以保持现在这样可以直接点弹窗其他界面直接关闭，这样效率也高

**Comment by Minxyzgo** [comment]
似乎没有必要，个人由于是平板习惯点关闭
