### ISSUE TITLE
开房间界面进行一些 ui 优化以及便利设定

### ISSUE THREAD

**Issue by Cogito-Official** [Minxyzgo/RWPP#43]
1、多人房间时新增 network received 进度，以及 mod 下载、重载进度。
2、房间设置（特别是沙盒）新增记忆上次设置，或预设功能，添加 ai 新增一键加满等（根本上是因为 rwpp 支持了 100p，如果要加 ai 就要按 99 下。。希望新增预设和记忆等功能，每次调这种多 p 的设置太麻烦了），或者要不识别一下地图名，例如 20p 就自动设置上限为 20p。
3、修复 3teams 和 ffa 设置下的队伍号 auto 仍按 2teams 匹配的问题，例如 team3 应当是 C，team11 应当是 11，而不是 A 或 B，在混战中如果玩家换位置，仍按 auto 来就会变成 A 或 B，此时房主经常要纠正错误，十分麻烦
4、希望 mod 管理界面可以不仅仅按原版的界面来，环世界、文明等的 mod 管理界面支持很多筛选，启用和未启用也会分开，希望橄榄 luke 丑陋界面，另外原版支持直接 delete，查看地图，是否可以支持一下呢？

**Comment by Minxyzgo** [comment]
你好，可以分出几个小的issue，这样方便分别完成。另外delete在pc端上是无法实现的，为了减小各平台的差异，我可能不会实现这个功能

**Comment by Cogito-Official** [comment]
感谢，我分一下
