### ISSUE TITLE
房间、战役室添加“一键加满AI”功能

### ISSUE THREAD

**Issue by Cogito-Official** [Minxyzgo/RWPP#45]
在沙盒、多人战役室等，可否在加ai的按钮旁边再加一个“一键加满AI” 这种功能呢？因为 rwpp 支持了 100p，如果要加 ai 就要按 99 下，虽然是极端情况，不过对于20p、30p等地图，加满AI也还是挺方便的（特别是手动加超出上限，在pc上，会在游戏进入后提示“no free slots for AI”）

**Comment by Minxyzgo** [comment]
实现为长按添加10个ai
