### ISSUE TITLE
自动位置存在错位（存疑）

### ISSUE THREAD

**Issue by Cogito-Official** [Minxyzgo/RWPP#54]
team11的队伍号在自动下是K，这导致12的队伍号是11,13的是12，依此类推。通常而言，10以内是A到J，但11应该是11而不是K。
在这种情况下，目前发现队伍14的队伍颜色不正确，其队伍号系13。除此之外队伍颜色均正确显示，即11为绿色，12为红色，13为蓝色，但14理应是黄色（即对应team4，但被显示为白色），如下图
![image](https://github.com/user-attachments/assets/6c45e81b-ae88-4696-bd85-e8aa241a7096)
问题出现版本：1.2.1、1.3.0beta1
若手动更改11为11,12为12队伍号的话，颜色又会不正确，希望作者优化一下

**Comment by Cogito-Official** [comment]
![image](https://github.com/user-attachments/assets/2be0abf4-cf7d-42ff-bb2a-15ebfabcd0a8)
补充一下，似乎是随机在一个位置出现，而且是此位置颜色被替换为白色，如图我重试了一次，结果是17（队伍16）变成了白色

**Comment by Cogito-Official** [comment]
再试了一次，我发现只要顺序是![image](https://github.com/user-attachments/assets/718c219f-d3f2-4c8b-bc4d-956f54c9b47c)
就一定是team11（阵营K，应为绿色）被替换为白色，经过多次测试，发现此根据玩家位置而定，如果玩家为team1，则team11被替换为白色，如果是team4，则是team14被替换，刚刚试了下team8就是team18被替换

**Comment by Minxyzgo** [comment]
11为J而不是11是原版的设定，原版队伍的实际值就是出生点-1，只是原版对1-11特殊处理成了A-K，而对于11以上则显示原本的team值，rwpp只是沿袭了原版的设定，至于颜色问题，这应该是原版的bug，rwpp目前没有修复原版bug的打算
