### ISSUE TITLE
多人游戏添加默认列表

### ISSUE THREAD

**Issue by Mitpoppy** [Minxyzgo/RWPP#58]
多人游戏进入后可以选择官方服务器列表作为默认列表，然后在其他地方做可选添加room列表或者独立服务器，并且可作固定显示（可设置密码取消） ，这样可以做作为参赛客户端使用

**Comment by Minxyzgo** [comment]
没有看懂和已有的有什么区别

**Comment by Mitpoppy** [comment]
> 没有看懂和已有的有什么区别

说白了就是点多人游戏时直接进入默认官方服务器列表，而选择服务器列表放另外一个地方

**Comment by Mitpoppy** [comment]
> > > 没有看懂和已有的有什么区别
> > 
> > 说白了就是点多人游戏时直接进入我选择的固定一个服务器列表，比如官方服务器列表，而选择服务器列表的地方放另外一个地方
> 
> 不是已经有一个`用作默认房间列表`吗

emmm不知道怎么解释，还是关了叭，我语言组织不出来了
