### ISSUE TITLE
mod 联机时若游戏崩溃则几乎无法再次加入

### ISSUE THREAD

**Issue by Cogito-Official** [Minxyzgo/RWPP#60]
如果难解决可以忽略，由于游戏重启后下载的 mod 会删除，如果想再次加入运行中游戏则无法加入（当然也不可能能传输），或许如果是非正常退出就不删除 mod？

**Comment by Cogito-Official** [comment]
想到了一种逻辑，联机时 mod 可以专门分离为一个独立的分区，每次新增就会覆盖掉，玩家可以随时直接把它变更为本地（保留），而不会自动移除

**Comment by Minxyzgo** [comment]
> 想到了一种逻辑，联机时 mod 可以专门分离为一个独立的分区，每次新增就会覆盖掉，玩家可以随时直接把它变更为本地（保留），而不会自动移除

目前是可以在下载完mod后进入模组界面取消删除模组，但是没有做分区
事实上逻辑就是启动时删除模组文件夹中后缀为.netbak的模组，手动更改为.rwmod也可以阻止

**Comment by Cogito-Official** [comment]
> > 想到了一种逻辑，联机时 mod 可以专门分离为一个独立的分区，每次新增就会覆盖掉，玩家可以随时直接把它变更为本地（保留），而不会自动移除
> 
> 目前是可以在下载完mod后进入模组界面取消删除模组，但是没有做分区 事实上逻辑就是启动时删除模组文件夹中后缀为.netbak的模组，手动更改为.rwmod也可以阻止

嗯，这个主要是对于“普通玩家”，特别是一些手机玩家，游戏崩溃了就会直接重启然后尝试加回上一次游戏，这样 mod 就直接删了

**Comment by Cogito-Official** [comment]
> > > 想到了一种逻辑，联机时 mod 可以专门分离为一个独立的分区，每次新增就会覆盖掉，玩家可以随时直接把它变更为本地（保留），而不会自动移除
> > 
> > 
> > 目前是可以在下载完mod后进入模组界面取消删除模组，但是没有做分区 事实上逻辑就是启动时删除模组文件夹中后缀为.netbak的模组，手动更改为.rwmod也可以阻止
> 
> 嗯，这个主要是对于“普通玩家”，特别是一些手机玩家，游戏崩溃了就会直接重启然后尝试加回上一次游戏，这样 mod 就直接删了

我的想法是这样的：rwpp 让很多原版 mod 装搞不明白的玩家大大降低了门槛。我发现好多新玩家完全不会装 mod，连文件管理都用不明白，我感觉让他们去找到 mod 路径改后缀名，就跟用原版装 mod 没什么难度差别了

**Comment by Minxyzgo** [comment]
最终还是决定不会实现，主要是因为崩溃毕竟小概率事件，其次是删除模组优先级较高，现有模型下实现该功能较难
